# Defines the configuration version.
# The only possible value is "2".
version: "2"
linters:
  enable:
    - cyclop
    - err113
    - errname
    - exhaustive
    - exptostd
    - gocritic
    - revive
formatters:
  enable:
    - gofumpt
    - goimports
    - golines
  settings:
    goimports:
        local-prefixes:
          - github.com/erdnaxeli/wishlister
