// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: create-group.sql

package repository

import (
	"context"
)

const createGroup = `-- name: CreateGroup :exec
insert into groups (
    id, name
)
values (
    ?, ?
)
`

type CreateGroupParams struct {
	ID   string
	Name string
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) error {
	_, err := q.db.ExecContext(ctx, createGroup, arg.ID, arg.Name)
	return err
}
