// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: delete-user-session.sql

package repository

import (
	"context"
)

const deleteUserSession = `-- name: DeleteUserSession :exec
delete from user_sessions
where id = ?
`

func (q *Queries) DeleteUserSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUserSession, id)
	return err
}
