// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: delete-wishlist-elements.sql

package repository

import (
	"context"
)

const deleteWishListElements = `-- name: DeleteWishListElements :exec
delete from wishlist_elements
where wishlist_id = ?
`

func (q *Queries) DeleteWishListElements(ctx context.Context, wishlistID string) error {
	_, err := q.db.ExecContext(ctx, deleteWishListElements, wishlistID)
	return err
}
