// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get-user-session-by-magic-link.sql

package repository

import (
	"context"
	"database/sql"
)

const getUserSessionByMagicLink = `-- name: GetUserSessionByMagicLink :one
update user_sessions
set magic_link_token = null
where magic_link_token = ?
    -- safety check to ensure the given token is not null
    and magic_link_token is not null
returning id, user_id
`

type GetUserSessionByMagicLinkRow struct {
	ID     string
	UserID string
}

func (q *Queries) GetUserSessionByMagicLink(ctx context.Context, magicLinkToken sql.NullString) (GetUserSessionByMagicLinkRow, error) {
	row := q.db.QueryRowContext(ctx, getUserSessionByMagicLink, magicLinkToken)
	var i GetUserSessionByMagicLinkRow
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}
