// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get-or-create-user.sql

package repository

import (
	"context"
)

const getOrCreateUser = `-- name: GetOrCreateUser :one
insert into users (id, name, email)
values (?, ?, ?)
on conflict (email) do update set name = excluded.name
returning id, name, email
`

type GetOrCreateUserParams struct {
	ID    string
	Name  string
	Email string
}

func (q *Queries) GetOrCreateUser(ctx context.Context, arg GetOrCreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateUser, arg.ID, arg.Name, arg.Email)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}
