// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get-user-session.sql

package repository

import (
	"context"
)

const getUserSession = `-- name: GetUserSession :one
select
    user_sessions.id,
    user_id,
    users.name as username,
    users.email as user_email
from user_sessions
join users on users.id = user_sessions.user_id
where user_sessions.id = ?
`

type GetUserSessionRow struct {
	ID        string
	UserID    string
	Username  string
	UserEmail string
}

func (q *Queries) GetUserSession(ctx context.Context, id string) (GetUserSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getUserSession, id)
	var i GetUserSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.UserEmail,
	)
	return i, err
}
