// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get-user-wishlists.sql

package repository

import (
	"context"
)

const getUserWishLists = `-- name: GetUserWishLists :many
select id, admin_id, name
from wishlists
where user_id = ?
`

type GetUserWishListsRow struct {
	ID      string
	AdminID string
	Name    string
}

func (q *Queries) GetUserWishLists(ctx context.Context, userID string) ([]GetUserWishListsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserWishLists, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserWishListsRow
	for rows.Next() {
		var i GetUserWishListsRow
		if err := rows.Scan(&i.ID, &i.AdminID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
