// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get-wishlist-elements.sql

package repository

import (
	"context"
	"database/sql"
)

const getWishListElements = `-- name: GetWishListElements :many
select
    id,
    name,
    description,
    url
from wishlist_elements
where wishlist_id = ?
`

type GetWishListElementsRow struct {
	ID          string
	Name        string
	Description sql.NullString
	Url         sql.NullString
}

func (q *Queries) GetWishListElements(ctx context.Context, wishlistID string) ([]GetWishListElementsRow, error) {
	rows, err := q.db.QueryContext(ctx, getWishListElements, wishlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWishListElementsRow
	for rows.Next() {
		var i GetWishListElementsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
