// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get-wishlist.sql

package repository

import (
	"context"
	"database/sql"
)

const getWishList = `-- name: GetWishList :one
select
    wishlists.id,
    admin_id,
    group_id,
    wishlists.name,
    users.name as username
from wishlists
join users on wishlists.user_id = users.id
where wishlists.id = ?
`

type GetWishListRow struct {
	ID       string
	AdminID  string
	GroupID  sql.NullString
	Name     string
	Username string
}

func (q *Queries) GetWishList(ctx context.Context, id string) (GetWishListRow, error) {
	row := q.db.QueryRowContext(ctx, getWishList, id)
	var i GetWishListRow
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.GroupID,
		&i.Name,
		&i.Username,
	)
	return i, err
}
