// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get-user-session.sql

package repository

import (
	"context"
)

const getUserSession = `-- name: GetUserSession :one
select
    id,
    user_id
from user_sessions
where id = ?
`

func (q *Queries) GetUserSession(ctx context.Context, id string) (UserSession, error) {
	row := q.db.QueryRowContext(ctx, getUserSession, id)
	var i UserSession
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}
