// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: insert-wishlist-element.sql

package repository

import (
	"context"
	"database/sql"
)

const insertWishListElement = `-- name: InsertWishListElement :exec
insert into wishlist_elements (
    id,
    wishlist_id,
    name,
    description,
    url
) values (
    ?, ?, ?, ?, ?
)
`

type InsertWishListElementParams struct {
	ID          string
	WishlistID  string
	Name        string
	Description sql.NullString
	Url         sql.NullString
}

func (q *Queries) InsertWishListElement(ctx context.Context, arg InsertWishListElementParams) error {
	_, err := q.db.ExecContext(ctx, insertWishListElement,
		arg.ID,
		arg.WishlistID,
		arg.Name,
		arg.Description,
		arg.Url,
	)
	return err
}
